import { promises as fs } from 'node:fs';
import path from 'node:path';
import { afterAll, beforeAll, describe, expect, it } from 'vitest';
import { Client } from '@modelcontextprotocol/sdk/client/index.js';
import { StdioClientTransport } from '@modelcontextprotocol/sdk/client/stdio.js';
import { copyFixture, readDoc, repoRoot, rmrf, exists } from '../helpers.js';
import type { ToolResultReport } from '../../src/types.js';

/**
 * End-to-end test (T052): spawn the real server over stdio with the MCP client SDK,
 * verify all four tools and run the full quickstart §5 acceptance-smoke flow.
 */
describe('end-to-end over stdio (quickstart §5)', () => {
  let workspace: string;
  let client: Client;

  beforeAll(async () => {
    workspace = await copyFixture('multi-lang', 'wmap-e2e-');
    client = new Client({ name: 'e2e-test', version: '0.0.0' });
    const transport = new StdioClientTransport({
      command: process.execPath,
      args: ['--import', 'tsx', 'src/index.ts', '--workspace', workspace],
      cwd: repoRoot,
      stderr: 'ignore',
    });
    await client.connect(transport);
  }, 60000);

  afterAll(async () => {
    await client?.close();
    if (workspace) await rmrf(workspace);
  });

  async function call(name: string, args: Record<string, unknown> = {}): Promise<ToolResultReport> {
    const result = await client.callTool({ name, arguments: args });
    const content = (result.content as Array<{ type: string; text: string }>)[0];
    expect(content.type).toBe('text');
    return JSON.parse(content.text) as ToolResultReport;
  }

  it('lists all four tools with schemas', async () => {
    const { tools } = await client.listTools();
    const names = tools.map((t) => t.name).sort();
    expect(names).toEqual(['install_guidance', 'scan_relations', 'scan_structure', 'update_maps']);
    for (const tool of tools) {
      expect(tool.inputSchema).toBeDefined();
      expect(tool.description).toBeTruthy();
    }
  });

  it('quickstart row 1 (US1): scan_structure writes structure.md with timestamp + exclusions', async () => {
    const report = await call('scan_structure');
    expect(report.status).toBe('success');
    const doc = await readDoc(workspace, '.codemap/structure.md');
    expect(doc).toContain('> Generated by workspace-map-mcp');
    expect(doc).toContain('## Exclusions applied');
    expect(doc).toContain('# src/web/app.ts');
  });

  it('quickstart row 2 (US2): scan_relations maps a known class with inheritance', async () => {
    const report = await call('scan_relations');
    expect(['success', 'partial']).toContain(report.status);
    const doc = await readDoc(workspace, '.codemap/relations.md');
    expect(doc).toContain('| `OrderService` | class | `Contoso.Orders` | src/csharp/OrderService.cs |');
    expect(doc).toContain('`ServiceBase` → `Contoso.Core.ServiceBase` (src/csharp/ServiceBase.cs)');
  });

  it('quickstart row 4 (US4): install_guidance adds the managed block', async () => {
    const report = await call('install_guidance');
    expect(report.status).toBe('success');
    const instructions = await readDoc(workspace, '.github/copilot-instructions.md');
    expect(instructions).toContain('<!-- BEGIN workspace-map-mcp -->');
    expect(await exists(path.join(workspace, '.github/skills/workspace-map/SKILL.md'))).toBe(true);
  });

  it('quickstart row 3 (US3): rename a file → update_maps removes the old path everywhere', async () => {
    await fs.rename(
      path.join(workspace, 'src', 'py', 'zoo.py'),
      path.join(workspace, 'src', 'py', 'kennel.py'),
    );
    const report = await call('update_maps');
    expect(report.counts.mode).toBe('incremental');

    const structure = await readDoc(workspace, '.codemap/structure.md');
    expect(structure).not.toContain('zoo.py');
    expect(structure).toContain('# src/py/kennel.py');
    const relations = await readDoc(workspace, '.codemap/relations.md');
    expect(relations).not.toContain('zoo.py');
    expect(relations).toContain('src/py/kennel.py');
  });

  it('quickstart row 5 (US4-AS4): re-running install_guidance keeps exactly one managed block', async () => {
    const report = await call('install_guidance');
    expect(report.counts.sectionAction).toBe('replaced');
    const instructions = await readDoc(workspace, '.github/copilot-instructions.md');
    expect(instructions.split('<!-- BEGIN workspace-map-mcp -->').length - 1).toBe(1);
  });

  it('rejects invalid input with an error report, no side effects', async () => {
    const result = await client.callTool({
      name: 'update_maps',
      arguments: { force: 'yes-please' },
    });
    // SDK-level schema rejection or tool-level error report are both acceptable.
    const text = (result.content as Array<{ type: string; text: string }>)[0]?.text ?? '';
    expect(result.isError === true || text.includes('"status": "error"') || text.includes('Invalid')).toBe(
      true,
    );
  });
});
