import { promises as fs } from 'node:fs';
import path from 'node:path';
import { afterEach, describe, expect, it } from 'vitest';
import { Client } from '@modelcontextprotocol/sdk/client/index.js';
import { StreamableHTTPClientTransport } from '@modelcontextprotocol/sdk/client/streamableHttp.js';
import { copyFixture, freePort, readDoc, rmrf, sleep, spawnServer, waitForReady } from '../helpers.js';
import type { ToolResultReport } from '../../src/types.js';

/**
 * HTTP transport edge cases (T018): port conflicts (US2-AS3), concurrent-client
 * serialization (US2-AS4, FR-009), stdio-when-no-flag regression (US2-AS2),
 * missing --port validation, and graceful shutdown draining (US2-AS5).
 */

describe('HTTP transport edges (US2-AS2..AS5)', () => {
  const cleanups: Array<() => Promise<void> | void> = [];

  afterEach(async () => {
    while (cleanups.length) await cleanups.pop()!();
  });

  async function tempWorkspace(): Promise<string> {
    const ws = await copyFixture('multi-lang', 'wmap-httpedge-');
    cleanups.push(() => rmrf(ws));
    return ws;
  }

  function report(result: Awaited<ReturnType<Client['callTool']>>): ToolResultReport {
    return JSON.parse((result.content as Array<{ text: string }>)[0].text) as ToolResultReport;
  }

  it('second instance on the same port exits non-zero with a clear error (US2-AS3)', async () => {
    const ws = await tempWorkspace();
    const port = await freePort();
    const first = spawnServer(['--workspace', ws, '--http', '--port', String(port)]);
    cleanups.push(() => void first.kill('SIGKILL'));
    await waitForReady(first);

    const second = spawnServer(['--workspace', ws, '--http', '--port', String(port)]);
    const code = await new Promise<number | null>((resolve) => second.once('exit', resolve));
    expect(code).toBe(1);
    expect(second.stderrText()).toContain(`port ${port} is already in use`);
  }, 60000);

  it('two concurrent HTTP clients are serialized; outputs uncorrupted (US2-AS4, FR-009)', async () => {
    const ws = await tempWorkspace();
    const port = await freePort();
    const server = spawnServer(['--workspace', ws, '--http', '--port', String(port)]);
    cleanups.push(() => void server.kill('SIGKILL'));
    await waitForReady(server);

    const url = new URL(`http://127.0.0.1:${port}/mcp`);
    const clientA = new Client({ name: 'edge-a', version: '0.0.0' });
    const clientB = new Client({ name: 'edge-b', version: '0.0.0' });
    await clientA.connect(new StreamableHTTPClientTransport(url));
    await clientB.connect(new StreamableHTTPClientTransport(url));
    cleanups.push(() => clientA.close().catch(() => {}));
    cleanups.push(() => clientB.close().catch(() => {}));

    const [relations, structure] = await Promise.all([
      clientA.callTool({ name: 'scan_relations', arguments: {} }),
      clientB.callTool({ name: 'scan_structure', arguments: {} }),
    ]);
    const relReport = report(relations);
    const structReport = report(structure);
    expect(['success', 'partial']).toContain(relReport.status);
    expect(structReport.status).toBe('success');

    // The mutex serialized them: whichever ran second waited on the other.
    const warnings = [...relReport.warnings, ...structReport.warnings];
    expect(warnings.some((w) => w.includes('queued for'))).toBe(true);

    // Outputs are complete and uncorrupted.
    const structureDoc = await readDoc(ws, '.codemap/structure.md');
    expect(structureDoc).toContain('> Generated by workspace-map-mcp');
    expect(structureDoc).toContain('# src/web/app.ts');
    const relationsDoc = await readDoc(ws, '.codemap/relations.md');
    expect(relationsDoc).toContain('| `OrderService` | class |');
  }, 90000);

  it('launch without --http still serves stdio with the unchanged ready log (US2-AS2)', async () => {
    const ws = await tempWorkspace();
    const server = spawnServer(['--workspace', ws]);
    cleanups.push(() => void server.kill('SIGKILL'));
    await waitForReady(server);
    const log = server.stderrText();
    expect(log).toMatch(/\[workspace-map-mcp\] v[\d.]+ ready — workspace: /);
    expect(log).not.toContain('transport: http');
  }, 30000);

  it('--http without --port fails with an actionable error', async () => {
    const ws = await tempWorkspace();
    const server = spawnServer(['--workspace', ws, '--http']);
    const code = await new Promise<number | null>((resolve) => server.once('exit', resolve));
    expect(code).toBe(1);
    expect(server.stderrText()).toContain('--port is required with --http.');
  }, 30000);

  // POSIX-only: Windows cannot deliver a catchable SIGTERM (process.kill → TerminateProcess).
  // CI (ubuntu) exercises this path; atomic-write guarantees are additionally unit-tested.
  it.runIf(process.platform !== 'win32')(
    'graceful shutdown: SIGTERM mid-flight drains, exits 0, maps never half-written (US2-AS5)',
    async () => {
      const ws = await tempWorkspace();
      const port = await freePort();
      const server = spawnServer(['--workspace', ws, '--http', '--port', String(port)]);
      await waitForReady(server);

      const client = new Client({ name: 'edge-drain', version: '0.0.0' });
      await client.connect(new StreamableHTTPClientTransport(new URL(`http://127.0.0.1:${port}/mcp`)));
      cleanups.push(() => client.close().catch(() => {}));

      const inFlight = client.callTool({ name: 'scan_relations', arguments: {} });
      await sleep(150); // let the scan start
      server.kill('SIGTERM');

      // In-flight work completes (or fails cleanly) — never hangs, never corrupts.
      const result = await inFlight;
      expect(['success', 'partial']).toContain(report(result).status);

      const code = await new Promise<number | null>((resolve) => server.once('exit', resolve));
      expect(code).toBe(0);

      // No temp remnants; maps well-formed.
      const codemap = await fs.readdir(path.join(ws, '.codemap'));
      expect(codemap.filter((f) => f.includes('.tmp'))).toEqual([]);
      const relationsDoc = await readDoc(ws, '.codemap/relations.md');
      expect(relationsDoc).toContain('> Generated by workspace-map-mcp');
    },
    60000,
  );
});
