import { CODEMAP_DIR, SERVER_NAME } from '../version.js';

/**
 * Agent skill content (FR-009, T043): teaches AI assistants to consult the maps
 * instead of searching, and to refresh them via update_maps when stale.
 */
export function skillMarkdown(): string {
  return `---
name: workspace-map
description: Navigate this workspace using the generated maps in ${CODEMAP_DIR}/ — structure.md to resolve any relative file path, relations.md to jump straight to a type's defining file — instead of workspace-wide searching. Refresh stale maps with the update_maps tool on the ${SERVER_NAME} MCP server.
---

# Workspace Map Skill

## When to use

- You need the relative path of a file → read \`${CODEMAP_DIR}/structure.md\` instead of listing directories.
- You need to find where a class/type/interface is defined, its parents, or what it imports/calls → read \`${CODEMAP_DIR}/relations.md\` instead of searching the codebase.
- The workspace changed (files added/removed/renamed, classes changed) or the maps look out of date → call the \`update_maps\` tool on the \`${SERVER_NAME}\` MCP server.

## How to read the maps

1. **\`${CODEMAP_DIR}/structure.md\`** — full folder/file tree. Every file line ends with a \`# relative/path\` comment: copy that path verbatim. Large workspaces are partitioned per top-level folder into \`${CODEMAP_DIR}/structure/<folder>.md\` (see the Partitions table in the root document).
2. **\`${CODEMAP_DIR}/relations.md\`** — start at the **Type index** table (Type | Kind | Qualifier | Defined in) to map a type name to its defining file. Watch for the name-collision warning: identical type names are disambiguated by qualifier (namespace/module). Per-type sections list inheritance, implemented interfaces, and best-effort call references. **File dependencies** shows import/using edges between files.

## Staleness check

Each document header carries a \`Generated by … on <timestamp>\` line. If the timestamp predates recent workspace changes, or a path you read does not exist, call \`update_maps\` (incremental, fast) before trusting the maps. Use \`{"force": true}\` to rebuild from scratch.

## Tools on the ${SERVER_NAME} server

| Tool | Purpose |
|---|---|
| \`scan_structure\` | (Re)generate the structure map |
| \`scan_relations\` | (Re)generate the relation map |
| \`update_maps\` | Refresh both maps incrementally (full generation fallback) |
| \`install_guidance\` | Reinstall this skill + the copilot-instructions guidance section |
`;
}

export const SKILL_REL_PATH = '.github/skills/workspace-map/SKILL.md';
