import type { ExclusionsSummary } from '../core/ignoreRules.js';
import { CODEMAP_DIR, MAP_FORMAT_VERSION, VERSION } from '../version.js';

/**
 * Common metadata header for all generated documents (FR-008, contracts/map-formats.md).
 */
export function renderHeader(
  title: string,
  generatedAt: string,
  workspaceName: string,
  metrics: Array<[string, number | string]>,
  exclusions: ExclusionsSummary,
): string[] {
  const lines: string[] = [];
  lines.push(`# ${title}`);
  lines.push('');
  lines.push(`> Generated by workspace-map-mcp v${VERSION} on ${generatedAt}`);
  lines.push(`> Workspace: ${workspaceName}`);
  lines.push(`> Format version: ${MAP_FORMAT_VERSION}`);
  lines.push('');
  lines.push('| Metric | Value |');
  lines.push('|---|---|');
  for (const [name, value] of metrics) {
    lines.push(`| ${name} | ${value} |`);
  }
  lines.push('');
  lines.push('## Exclusions applied');
  lines.push('');
  lines.push(`- Built-in defaults: ${exclusions.builtIn.map((e) => `\`${e}\``).join(', ')}`);
  lines.push(
    `- From .gitignore: ${exclusions.gitignoreRules} rule(s) across ${exclusions.gitignoreFiles} file(s)`,
  );
  lines.push(
    `- User include patterns: ${
      exclusions.userInclude.length ? exclusions.userInclude.map((p) => `\`${p}\``).join(', ') : 'none'
    }`,
  );
  lines.push(
    `- User exclude patterns: ${
      exclusions.userExclude.length ? exclusions.userExclude.map((p) => `\`${p}\``).join(', ') : 'none'
    }`,
  );
  lines.push('');
  return lines;
}

export function codemapPath(fileName: string): string {
  return `${CODEMAP_DIR}/${fileName}`;
}
